### PR TITLE
Postcodes management functionality

### PR DESCRIPTION
**Pull request by remixaz**
Added new module page and functionality for Romania postcodes management.
Fixed issue of wrongly searched postcode by address, state and city.
Removed unused fields and data for postcode search.
Updated module version and added upgrade functionality.

### CODE REVIEW

**Comment by gfanton** [comment]
hello @remixaz,

It's look like your module fail to upgrade from 0.1.0 to 1.0.0 .

dpdgroup-upgrade-fail

Tested on PrestaShop 1.6.1.1

Regads.

**Comment by remixaz** [comment]
Hello @gfanton ,
I have rechecked upgrade functionality, fixed this issue and commited changes, please check them now.
Regads.

**Comment by gfanton** [comment]
Hello @remixaz i got another error now:

dpdupdate-error
Regards.

**Comment by remixaz** [comment]
Hello @gfanton , 
as I understand, You continued testing this module upgrade functionality on Your old database where the first error appeared.
Error appears because on Your old database there is still not deleted database table index "postcode_2" which includes missing "road_type" table column.
Currently after last module fix it firstly deletes index "postcode_2", then removes column "road_type" and then creates new index "postcode_2".
Naturally this situation should not appear upgrading module from 0.1.0 to 1.0.0 version.
Please reinstall old module in order not to get this error again.

**Comment by gfanton** [comment]
Hello @remixaz,

I actually test your module with a docker image of prestashop.
Everytime, I test your module on a fresh instance (so there are no conflicts with others modules, databases etc..)
I clone your module directly on this docker from PrestaShop/dpdgroup master and install it.
Then I checkout your repo (remixaz-master master) and pull your last commit.
I just have to refresh the module page to lunch the update.
So i don't think it's a database corruption.

Regads.

**Comment by remixaz** [comment]
Hello @gfanton ,

Finally I was able to reproduce this issue, the problem was in old module data which is already removed in new module version.
I have improved module upgrade functionality adding logic to remove duplicated data from database table before creating unique key. Now no errors should appear during module upgrade.
Please check the changes now.

Regards.

**Comment by gfanton** [comment]
Hello @remixaz ,

Perfect :thumbsup:
Your PR is now merged.

**Pull request merged**
